Sasha
AdayevKP/TaskTracker pull request #4
Opened 2021-01-16 22:34 UTC by sandelete

2021-01-17 10:02 UTC, AdayevKP requested changes

2021-01-17 10:30 UTC, sandelete commented on frontend/src/taskTrackerApp/taskTracker.js
> -        const week_raw = '{"days":[{"name": "MON", "date": "23.08", "sessions": [{"task": {"id": 1,"name": "Work","color":"#fccf50","active": true}, "duration": 4.2}, {"task": {"id": 2, "name": "Stud
Да я это понимаю. Здесь я просто поправил, чтобы болванка отображалась так как нужно мне для верстки. Мне от сервера нужен только объект даты и все. А потом его преобразовать в дату и день недели вообще изи.

2021-01-17 10:32 UTC, AdayevKP commented on frontend/src/taskTrackerApp/taskTracker.js
> -        const week_raw = '{"days":[{"name": "MON", "date": "23.08", "sessions": [{"task": {"id": 1,"name": "Work","color":"#fccf50","active": true}, "duration": 4.2}, {"task": {"id": 2, "name": "Stud
ну так и сделай сразу. это работы на 10 минут

2021-01-19 15:21 UTC, AdayevKP approved these changes

2021-01-19 15:22 UTC, merged